# Generated by Django 4.2.3 on 2023-08-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_accountbook_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbook',
            unique_together={('date',)},
        ),
    ]
