# Generated by Django 4.2.1 on 2023-08-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_accountbook_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbook',
            name='title',
        ),
    ]
