# Generated by Django 4.2.1 on 2023-08-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_accountbook_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbook',
            name='total',
        ),
    ]
